### ISSUE TITLE
Feedback zum Testat

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/repo-07#1]
Bitte korrigieren Sie die folgenden Fehler und checken Sie dann die korrigierte Version ein. Danach können Sie dieses Issue schließen.

  * JavaDoc ergänzen, diese fehlt vollständig
  * Ihre Implementierung geht nicht richtig mit Eingaben um, die ungültige Zeichen enthalten. Diese sollen stillschweigend entfernt werden.

**Comment by GurkenKater** [comment]
Also in der letzten Version hat der Encoder in der Ausgabe immer am Ende '\u0000' Elemente im String Objekt, wenn ungültige Zeichen enthalten waren. Das ist gefixt und JavaDoc ergänzt.
